name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker buildx build --builder=mcp-builder --platform linux/amd64,linux/arm64 -t ghcr.io/dinavinter/mcp-py-repl:$(date +%s) --push . --file Dockerfil      
      
