name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    permissions:
      packages: write # Grants write access to GitHub Packages
      contents: read  # Grants read access to repository contents (often needed for checkout)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
    - uses: crazy-max/ghaction-setup-docker@v2
      with:
        version: v24.0.6
        daemon-config: |
          {
            "features": {
              "containerd-snapshotter": true
            }
          }

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/dinavinter/mcp-py-repl:$(date +%s) --push . --file Dockerfile     
      
