name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Up contained image store
      shell: bash
      run: |
        cat /etc/docker/daemon.json | jq '. | .+{"features": {"containerd-snapshotter": true}}' | sudo tee /etc/docker/daemon.json
        cat /etc/docker/daemon.json
        sudo systemctl restart docker

        docker info -f '{{ .DriverStatus }}'
        docker info

    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/dinavinter/mcp-py-repl:$(date +%s) --push . --file Dockerfil      
      
