name: Docker Image CI
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push-image:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . 
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        outputs: type=image,name=target,annotation-index.org.opencontainers.image.source=https://github.com/octocat/my-repo,annotation-index.org.opencontainers.image.description=MCP Repl,annotation-index.org.opencontainers.image.licenses=MIT

